[ 2025-08-08 17:58:41,909 ] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.5:5000
[ 2025-08-08 17:58:41,909 ] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-08-08 17:59:04,642 ] 96 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 17:59:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2025-08-08 17:59:09,166 ] 96 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 17:59:09] "GET /predictdata HTTP/1.1" 200 -
[ 2025-08-08 17:59:26,251 ] 825 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "D:\DS-Project\Student-Performance-Indicator\src\utils.py", line 59, in load_object
    return pickle.load(file_obj)
AttributeError: Can't get attribute '_RemainderColsList' on <module 'sklearn.compose._column_transformer' from 'C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python38\\site-packages\\sklearn\\compose\\_column_transformer.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 18, in predict
    preprocessor=load_object(file_path=preprocessor_path)
  File "D:\DS-Project\Student-Performance-Indicator\src\utils.py", line 62, in load_object
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [D:\DS-Project\Student-Performance-Indicator\src\utils.py] line number [59] error message[Can't get attribute '_RemainderColsList' on <module 'sklearn.compose._column_transformer' from 'C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python38\\site-packages\\sklearn\\compose\\_column_transformer.py'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py", line 25, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [D:\DS-Project\Student-Performance-Indicator\src\pipeline\predict_pipeline.py] line number [18] error message[Error occured in python script name [D:\DS-Project\Student-Performance-Indicator\src\utils.py] line number [59] error message[Can't get attribute '_RemainderColsList' on <module 'sklearn.compose._column_transformer' from 'C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python38\\site-packages\\sklearn\\compose\\_column_transformer.py'>]]
[ 2025-08-08 17:59:26,256 ] 96 werkzeug - INFO - 127.0.0.1 - - [08/Aug/2025 17:59:26] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
